query($user: String!, $limit: Int!) {
    user(login: $user) {
        repositories(first: $limit, orderBy: {field: UPDATED_AT, direction: DESC}) {
            totalCount
            pageInfo {
                endCursor
                startCursor
                hasPreviousPage
                hasNextPage
            }
            nodes {
                id
                name
                updatedAt
                owner {
                    login
                }
            }
        }
    }
}